### PR TITLE
refine format short value

### LINKED ISSUE #471: Execution Count displays incorrectly when the value is too large
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

image

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

### PR DESCRIPTION
**Pull request by baurine**
close #471 

Screenshots:

image

image

### CODE REVIEW

**Comment by baurine** [comment]
hi @breeswish , we discussed this problem several weeks ago, we said to hack the `getValueFormat()` method, but I think maybe it is better to wrap it instead of hacking it, how do you think about?

**Comment by breeswish** [comment]
@baurine It is already recognized as a bug in grafana https://github.com/grafana/grafana/issues/23561 I think we can fix it by our own and not waiting for grafana to fix it, considering that the fix is extremely simple.

**Comment by baurine** [comment]
Got, as it is recognized as a bug by grafana (I thought it is by design), it makes sense to fix it, and I think we should commit a PR for it (will do it later).

**Comment by baurine** [comment]
I found this change changes the `scaledDecimals` original meaning (don't know what's its original meaning) totally and breaks too many upstream tests, so I release an incompatible version by changing version from 0.1.2 to 1.0.0 for grafana-value-formats lib.

**Pull request merged**
