### PR TITLE
keyvis: support to display DB Name

### PR DESCRIPTION
**Pull request by zzh-wisdom**
UCP #247 

## What have you changed? 

Add DB Name in the function `Label` of decorator
Change some parameters in ui/packages/keyvis/src/heatmap/chart.ts

## What are the type of the changes? 

Improvement

## How has this PR been tested? 

Run the following commands in order：
`make ui`
`UI=1 SWAGGER=1 make server`
`make run`
As a result, open the front end and display `DB Name` correctly

## Does this PR affect documentation (docs/docs-cn) update? 

No

### CODE REVIEW

**Comment by breeswish** [comment]
image

Looks like this PR will break some existing functionalities:
- In Y axis, row / index is no longer visible
- In tooltip, the label display looks incorrect..

**Comment by zzh-wisdom** [comment]
But running on my computer, the three columns of labels can be displayed correctly.
31584947453_ pic_hd
@breeswish

**Comment by breeswish** [comment]
Hi, please also update the tooltip label logic to correctly display the `mysql` table:

image

**Comment by breeswish** [comment]
@HunDunDM PTAL

**Pull request merged**
